// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokEOF-0]
	_ = x[TokLeftParen-1]
	_ = x[TokRightParen-2]
	_ = x[TokComma-3]
	_ = x[TokAssign-4]
	_ = x[TokPlus-5]
	_ = x[TokMinus-6]
	_ = x[TokAsterisk-7]
	_ = x[TokSlash-8]
	_ = x[TokCaret-9]
	_ = x[TokTilde-10]
	_ = x[TokBang-11]
	_ = x[TokQuestion-12]
	_ = x[TokColon-13]
	_ = x[TokName-14]
}

const _TokenType_name = "TokEOFTokLeftParenTokRightParenTokCommaTokAssignTokPlusTokMinusTokAsteriskTokSlashTokCaretTokTildeTokBangTokQuestionTokColonTokName"

var _TokenType_index = [...]uint8{0, 6, 18, 31, 39, 48, 55, 63, 74, 82, 90, 98, 105, 116, 124, 131}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
